# More option see https://github.com/DreamMaoMao/mango/wiki/

source=./animations.conf
source=./appearance.conf
source=./env.conf
source=./devices.conf
source=./layouts.conf
source=./keybind.conf
source=./misc.conf
source=./autostart.conf

source=./dms/colors.conf

