{
    config,
    osConfig,
    inputs,
    pkgs,
    ...
}:

let
    host = osConfig.networking.hostName;
    colors = config.lib.stylix.colors;
in
{
    home.packages = with pkgs; [
        grim
        slurp
        swappy
        cliphist
        grimblast
    ];

    xdg.configFile."hypr" = {
        source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/nix-dots/home/applications/hyprland/config";
        recursive = true;
    };

    # The stylix hyprland target only works through wayland.windowManager.hyprland,
    # which is not used here (config is a live Lua setup). Generate a colors file
    # from the active stylix scheme instead; it is required by hyprland/appearance.lua.
    home.file."nix-dots/home/applications/hyprland/config/hyprland/colors.lua".text = ''
        -- Generated by home-manager from the active stylix base16 scheme. Do not edit.
        return {
            base00 = "${colors.base00}",
            base01 = "${colors.base01}",
            base02 = "${colors.base02}",
            base03 = "${colors.base03}",
            base04 = "${colors.base04}",
            base05 = "${colors.base05}",
            base06 = "${colors.base06}",
            base07 = "${colors.base07}",
            base08 = "${colors.base08}",
            base09 = "${colors.base09}",
            base0A = "${colors.base0A}",
            base0B = "${colors.base0B}",
            base0C = "${colors.base0C}",
            base0D = "${colors.base0D}",
            base0E = "${colors.base0E}",
            base0F = "${colors.base0F}",
        }
    '';

    home.file."nix-dots/home/applications/hyprland/config/hyprland/monitor.lua" = {
        source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/nix-dots/home/applications/hyprland/overrides/${host}/monitor.lua";
    };

    home.file."nix-dots/home/applications/hyprland/config/hyprland/workspaces.lua" = {
        source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/nix-dots/home/applications/hyprland/overrides/${host}/workspaces.lua";
    };
}
