monitor=eDP-1,1920x1080@60.02,0x0,1

$terminal = kitty --single-instance
$fileManager = nautilus
$menu = dms ipc call spotlight toggle
$browser = qutebrowser

source=./animations.conf
source=./appearance.conf
source=./autostart.conf
source=./env.conf
source=./input.conf
source=./keybind.conf
source=./rules.conf
