$mod = SUPER

# 1. Applications
bind = $mod, T, exec, $terminal #"Open terminal"
bind = $mod, B, exec, $browser #"Open browser"
bind = $mod, E, exec, $fileManager #"Open file manager"
bind = $mod, space, exec, $menu  #"Open menu"
bind = $mod, U, exec, $terminal --execute btop #"Open btop"
bind = $mod, F, exec, $terminal --execute tmux-sessionizer
bindl = , XF86PickupPhone, exec, blueman-manager #"Open blueman"

# 2. Window Management
bind = $mod, Q, killactive #"Kill window"
bind = $mod, F11,fullscreen #"Toggle full screen"
bind = $mod, V, togglefloating #"Toggle floating"
bind = $mod SHIFT, V, exec, hyprctl dispatch togglefloating && \
    hyprctl dispatch resizeactive exact 50% 50% && \
    hyprctl dispatch centerwindow #"Toggle floating and center"

# 3. Move focus
bind = $mod, h, movefocus, l #"Move focus left"
bind = $mod, l, movefocus, r #"Move focus right"
bind = $mod, k, movefocus, u #"Move focus up"
bind = $mod, j, movefocus, d #"Move focus down"

# 4. Switch workspaces
bind = $mod, 1, workspace, 1 #"Workspace 1"
bind = $mod, 2, workspace, 2 #"Workspace 2"
bind = $mod, 3, workspace, 3 #"Workspace 3"
bind = $mod, 4, workspace, 4 #"Workspace 4"
bind = $mod, 5, workspace, 5 #"Workspace 5"
bind = $mod, 6, workspace, 6 #"Workspace 6"
bind = $mod, 7, workspace, 7 #"Workspace 7"
bind = $mod, 8, workspace, 8 #"Workspace 8"
bind = $mod, 9, workspace, 9 #"Workspace 9"
bind = $mod, 0, workspace, 10 #"Workspace 10"

# 5. Move windows
bind = $mod SHIFT, H, movewindow, l #"Move window left"
bind = $mod SHIFT, L, movewindow, r #"Move window right"
bind = $mod SHIFT, K, movewindow, u #"Move window up"
bind = $mod SHIFT, J, movewindow, d #"Move window down"

bind = $mod SHIFT, 1, movetoworkspace, 1 #"Move to Workspace 1"
bind = $mod SHIFT, 2, movetoworkspace, 2 #"Move to Workspace 2"
bind = $mod SHIFT, 3, movetoworkspace, 3 #"Move to Workspace 3"
bind = $mod SHIFT, 4, movetoworkspace, 4 #"Move to Workspace 4"
bind = $mod SHIFT, 5, movetoworkspace, 5 #"Move to Workspace 5"
bind = $mod SHIFT, 6, movetoworkspace, 6 #"Move to Workspace 6"
bind = $mod SHIFT, 7, movetoworkspace, 7 #"Move to Workspace 7"
bind = $mod SHIFT, 8, movetoworkspace, 8 #"Move to Workspace 8"
bind = $mod SHIFT, 9, movetoworkspace, 9 #"Move to Workspace 9"
bind = $mod SHIFT, 0, movetoworkspace, 10  #"Move to Workspace 10"

# 6. Resize windows
binde = $mod ALT, H, resizeactive, -20 0 #"Resize window left"
binde = $mod ALT, L, resizeactive, 20 0 #"Resize window right"
binde = $mod ALT, K, resizeactive, 0 -20 #"Resize window up"
binde = $mod ALT, J, resizeactive, 0 20 #"Resize window down"
bindm = $mod, mouse:272, movewindow #"Resize with mouse"
bindm = $mod, mouse:273, resizewindow #"Resize with mouse"

# 7. DMS Shell
bind = $mod CTRL, l, exec, dms ipc call lock lock
bind = $mod SHIFT, q, exec, dms ipc call powermenu toggle

# 8. Media Control
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ #"Increase volume"
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- #"Decrease volume"
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle #"Mute audio"
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle #"Mute mic"
bindl = , XF86AudioNext, exec, playerctl next #"Next audio"
bindl = , XF86AudioPause, exec, playerctl play-paus #"Pause audio"
bindl = , XF86AudioPlay, exec, playerctl play-pause #"Resume audio"
bindl = , XF86AudioPrev, exec, playerctl previous #"Previous audio"

# 9. Other FN-Binds
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+ #"Increase Brightness"
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%- #"Decrease Brightness"
bindl = , XF86NotificationCenter, exec, $terminal -e nvim ~/.config/hypr #"Edit hyprland config"

# 10. Screenshots
bind = , PRINT, exec, grimblast copysave area #"Screenshot window"
bind = SHIFT, PRINT, exec, grimblast copysave output #"Screenshot screen"
