# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class *

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Always float
windowrule = float match:class ^(protonvpn-app)$

# Center the window on spawn
windowrule = center match:class ^(protonvpn-app)$

# Set size to 50% of screen
windowrule = size 50% 50% match:class ^(protonvpn-app)$

layerrule = no_anim on, match:namespace ^(dms)$

