# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Always float
windowrulev2 = float,class:^(protonvpn-app)$

# Center the window on spawn
windowrulev2 = center,class:^(protonvpn-app)$

# Set size to 50% of screen
windowrulev2 = size 50% 50%,class:^(protonvpn-app)$

layerrule = blur, noctalia-background-.*$
layerrule = blurpopups, noctalia-background-.*$
layerrule = ignorealpha 0.7, noctalia-background-.*$

